---
title: "R5R"
output: html_document
---

```{r setup, include=FALSE}
options(java.parameters = "-Xmx8G")
knitr::opts_chunk$set(echo = TRUE)
# library("r5r")
library("tidyverse")
library("sf")
library("tmap")
library("mapproj")
library("lubridate")
library("purrr")
```

## 

```{r include=FALSE}
r5r_core <- setup_r5(system.file("extdata", package = "r5r"), verbose = FALSE)
```

```{r}
r5r_core$silentMode()
r5r_core$verboseMode()
r5r_core$setLogMode("ERROR")
r5r_core$setLogMode("OFF")
```

```{r}
fromLat <- -29.997611
fromLon <- -51.197720
toLat <- -30.048951
toLon <- -51.229533

origin <- tibble(id="1", lat = fromLat, lon = fromLon)
destination <- tibble(id="2", lat=toLat, lon = toLon)

trip_date <- "2019-03-20"
departure_time <- "14:00:00"
trip_date_time <- lubridate::as_datetime("2019-03-20 14:00:00")

street_time = 120L

paths_df <- detailed_itineraries(r5r_core = r5r_core, origins = origin, destinations = destination, 
                     departure_datetime = trip_date_time, max_walk_dist = 0.8, 
                     mode = c("WALK", "BICYCLE", "BUS"),
                     shortest_path = FALSE, verbose = FALSE, drop_geometry = FALSE)

```

```{r}
street_net <- street_network_to_sf(r5r_core)
```

```{r}
paths_df
```

```{r}
paths_df %>%
  ggplot() +
  # geom_sf(data=street_net$edges, colour="grey85", aes(geometry=geometry)) +
  geom_sf(aes(geometry=geometry, colour=mode)) +
  facet_wrap(~option)
```
```{r}

```


```{r}
paths_df %>%
  mutate(dist_m = distance, dist_geo = st_length(geometry)) %>% View()


  mutate(dist_sum = map_dbl(route, function(txt) {
           txt_list <- str_split(txt, pattern = " ", simplify = TRUE)
           num_list = as.numeric(txt_list)
           return(sum(num_list))
         }))
```


```{r}
paths_df %>% st_write("/Users/marcussaraiva/paths3.shp")
street_net$edges %>% st_write("/Users/marcussaraiva/streets.shp")
```


```{r}
points <- read_csv(system.file("extdata/poa_hexgrid.csv", package = "r5r"))
poi <- read_csv(system.file("extdata/poa_points_of_interest.csv", package = "r5r"))
```

```{r}

```

```{r}
ttm <- travel_time_matrix(r5r_core, points, points, departure_datetime = trip_date_time, 
                          mode=c("WALK", "BUS"), 
                          max_walk_dist = 500, max_trip_duration = 120L, verbose = FALSE)
```

```{r}
ttm
```




```{r}
orig <- (points %>% sample_n(4))$id

ttm %>% filter(fromId %in% orig) %>%
  left_join(points, by=c("toId" = "id")) %>%
  ggplot() +
  geom_point(data=points, aes(x=lon, y=lat), colour="grey85") +
  geom_point(aes(x=lon, y=lat, colour=travel_time)) +
  scale_color_distiller(palette = "Spectral") +
  coord_map() +
  facet_wrap(~fromId)
```

```{r}
# origins
"89a9012804fffff"

```






