name: R-CMD-check

on:
  workflow_run:
    workflows: ["Java R5RCore build"]
    types: [completed]

jobs:
  R-CMD-check:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release'}
          - {os: macOS-latest, r: 'release'}
          - {os: ubuntu-22.04, r: 'devel', rspm: "https://packagemanager.rstudio.com/cran/__linux__/jammy/latest"}
          - {os: ubuntu-22.04, r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/jammy/latest"}
          - {os: ubuntu-22.04, r: 'oldrel', rspm: "https://packagemanager.rstudio.com/cran/__linux__/jammy/latest"}

    env:
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@v2

      # Java setup for macOS (using the proper arm64 architecture)
      - name: Java setup (macOS)
        if: runner.os == 'macOS'
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'
          architecture: arm64

      # Java setup for non-macOS runners
      - name: Java setup (non-macOS)
        if: runner.os != 'macOS'
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
          working-directory: r-package

      - uses: r-lib/actions/check-r-package@v2
        with:
          working-directory: r-package
