on:
  workflow_run:
    workflows: ["Java R5RCore build"]
    types: [completed]

name: test-coverage

jobs:
  test-coverage:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2

      - name: Java setup
        uses: actions/setup-java@v1
        with:
          java-version: '21'
          java-package: jdk

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr, any::xml2
          needs: coverage
          working-directory: r-package

      - name: Test coverage
        run: |
          cov <- covr::package_coverage(
            quiet = FALSE,
            clean = FALSE,
            install_path = file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "package")
          )
          covr::to_cobertura(cov)
        shell: Rscript {0}
        working-directory: r-package

      - uses: codecov/codecov-action@v4
        with:
          # Fail if error if not on PR, or if on PR and token is given
          fail_ci_if_error: ${{ github.event_name != 'pull_request' || secrets.CODECOV_TOKEN }}
          file: ./cobertura.xml
          plugin: noop
          disable_search: true
          token: ${{ secrets.CODECOV_TOKEN }}
          working-directory: r-package
